"""Criação das tabelas

Revision ID: cf74a1973946
Revises: 
Create Date: 2024-12-23 20:53:58.465214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf74a1973946'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('status_pagamento', sa.String(length=20), nullable=False),
    sa.Column('data_contratacao', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('dominio', sa.String(length=100), nullable=False),
    sa.Column('hospedagem', sa.String(length=100), nullable=True),
    sa.Column('data_vencimento_hospedagem', sa.Date(), nullable=True),
    sa.Column('login_hospedagem_usuario', sa.String(length=100), nullable=True),
    sa.Column('login_hospedagem_senha', sa.String(length=100), nullable=True),
    sa.Column('login_painel_wordpress_usuario', sa.String(length=100), nullable=True),
    sa.Column('login_painel_wordpress_senha', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dominio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site')
    op.drop_table('cliente')
    # ### end Alembic commands ###
